export const items = [
  {
    id: 1,
    name: "Chicken Hell",
    image: "/images/food-1.png",
    tag: "Trending",
    duration: "24min",
    rating: "4.9",
    price: "12",
  },
  {
    id: 2,
    name: "Meat Heaven",
    image: "/images/food-2.png",
    tag: "Healthy",
    duration: "24min",
    rating: "4.9",
    price: "12",
  },
  {
    id: 3,
    name: "Chicken Hell",
    image: "/images/food-1.png",
    tag: "Trending",
    duration: "24min",
    rating: "4.9",
    price: "12",
  },
  {
    id: 4,
    name: "Meat Heaven",
    image: "/images/food-2.png",
    tag: "Healthy",
    duration: "24min",
    rating: "4.9",
    price: "12",
  },
  {
    id: 5,
    name: "Chicken Hell",
    image: "/images/food-1.png",
    tag: "Trending",
    duration: "24min",
    rating: "4.9",
    price: "12",
  },
];
